import { createServer } from "node:http";
import CDP from "chrome-remote-interface";
import { WebSocket, WebSocketServer } from "ws";
import {
	extractTargetId,
	formatTargetSummary,
	getNumberArg,
	getPrimaryInputArg,
	getStringArg,
	hasFlag,
	parseCliArgs,
	proxyJsonRequest,
	resolveDevtoolsTarget,
	toProxyWebSocketUrl,
	toUpstreamWebSocketUrl,
} from "./devtools-utils";
import type { DevtoolsListTarget } from "chrome-remote-interface";

interface BufferedLogEntry {
	id: number;
	kind: "console" | "exception" | "log";
	level: string;
	timestamp: string;
	text: string;
	location?: string;
}

interface AiBootstrapPayload {
	message: string;
	target: Record<string, unknown>;
	sourceInspectorUrl: string | null;
	shouldRead: Array<{
		name: string;
		url: string;
		purpose: string;
	}>;
	shouldNotRead: Array<{
		name: string;
		url: string;
		reason: string;
	}>;
}

type RuntimeConsoleCall = {
	type?: string;
	args?: Array<{ value?: unknown; description?: string; type?: string }>;
	timestamp?: number;
	stackTrace?: {
		callFrames?: Array<{
			url?: string;
			functionName?: string;
			lineNumber?: number;
			columnNumber?: number;
		}>;
	};
};

type RuntimeExceptionThrown = {
	timestamp?: number;
	exceptionDetails?: {
		text?: string;
		url?: string;
		lineNumber?: number;
		columnNumber?: number;
		exception?: {
			description?: string;
			value?: unknown;
		};
		stackTrace?: RuntimeConsoleCall["stackTrace"];
	};
};

type LogEntryAdded = {
	entry?: {
		level?: string;
		text?: string;
		source?: string;
		url?: string;
		lineNumber?: number;
	};
};

function formatTimestamp(timestamp?: number): string {
	if (!timestamp) return new Date().toISOString();
	const millis = timestamp > 1e12 ? timestamp : timestamp * 1000;
	return new Date(millis).toISOString();
}

function formatArgs(
	args: RuntimeConsoleCall["args"] = [],
): string {
	return args
		.map((arg) => {
			if ("value" in arg && arg.value !== undefined) {
				return typeof arg.value === "string"
					? arg.value
					: JSON.stringify(arg.value);
			}
			return arg.description ?? arg.type ?? "<unserializable>";
		})
		.join(" ");
}

function formatTopFrame(stackTrace?: RuntimeConsoleCall["stackTrace"]): string {
	const frame = stackTrace?.callFrames?.[0];
	if (!frame) return "";
	const location = frame.url
		? `${frame.url}:${(frame.lineNumber ?? 0) + 1}:${(frame.columnNumber ?? 0) + 1}`
		: "unknown";
	return frame.functionName ? `${frame.functionName} @ ${location}` : location;
}

function escapeHtml(input: string): string {
	return input
		.replaceAll("&", "&amp;")
		.replaceAll("<", "&lt;")
		.replaceAll(">", "&gt;")
		.replaceAll('"', "&quot;");
}

function rewriteTarget(
	target: DevtoolsListTarget,
	listenHost: string,
	listenPort: number,
): DevtoolsListTarget {
	return {
		...target,
		webSocketDebuggerUrl: target.webSocketDebuggerUrl
			? toProxyWebSocketUrl(listenHost, listenPort, target.webSocketDebuggerUrl)
			: target.webSocketDebuggerUrl,
	};
}

function createSyntheticTarget(
	resolved: Awaited<ReturnType<typeof resolveDevtoolsTarget>>,
	listenHost: string,
	listenPort: number,
): DevtoolsListTarget | null {
	if (!resolved.webSocketDebuggerUrl || !resolved.targetId) {
		return null;
	}

	const encodedWs = encodeURIComponent(
		`${listenHost}:${listenPort}/devtools/page/${resolved.targetId}`,
	);

	return {
		description: resolved.target?.description ?? "Synthetic target generated by proxy",
		devtoolsFrontendUrl: `/devtools/inspector.html?ws=${encodedWs}`,
		id: resolved.targetId,
		title: resolved.target?.title ?? "NetEase Cloud Music",
		type: resolved.target?.type ?? "page",
		url: resolved.target?.url ?? "orpheus://orpheus/pub/app.html",
		webSocketDebuggerUrl: toProxyWebSocketUrl(
			listenHost,
			listenPort,
			resolved.webSocketDebuggerUrl,
		),
	};
}

async function main() {
	const args = parseCliArgs();
	const input = getPrimaryInputArg(
		args,
		"target",
		"input",
		"url",
		"ws",
		"endpoint",
	);
	const targetIdArg = getStringArg(args, "target-id");
	const targetId = targetIdArg ?? extractTargetId(input);
	const urlContains = getStringArg(args, "url-contains");
	const listenPort = getNumberArg(args, ["listen-port", "port"], 9333);
	const listenHost = getStringArg(args, "listen-host") ?? "127.0.0.1";
	const exposeAll = hasFlag(args, "all", "expose-all");

	const resolved = await resolveDevtoolsTarget({
		input,
		targetId,
		urlContains,
	});
	const logBuffer: BufferedLogEntry[] = [];
	let nextLogId = 1;

	const appendLog = (entry: Omit<BufferedLogEntry, "id">) => {
		logBuffer.push({ id: nextLogId++, ...entry });
		if (logBuffer.length > 1000) {
			logBuffer.splice(0, logBuffer.length - 1000);
		}
	};

	const runtimeClient = resolved.webSocketDebuggerUrl
		? await CDP({ target: resolved.webSocketDebuggerUrl })
		: null;

	const bootstrapPayload: AiBootstrapPayload = {
		message:
			"AI should read the real target APIs exposed by this proxy, not the inspector.html container page.",
		target: formatTargetSummary(resolved),
		sourceInspectorUrl: input ?? null,
		shouldRead: [
			{
				name: "Bootstrap",
				url: `http://${listenHost}:${listenPort}/api/bootstrap`,
				purpose: "Single source of truth for AI-safe endpoints and target metadata.",
			},
			{
				name: "Target",
				url: `http://${listenHost}:${listenPort}/api/target`,
				purpose: "Read the resolved real NetEase Cloud Music target.",
			},
			{
				name: "Logs",
				url: `http://${listenHost}:${listenPort}/api/logs?recent=50`,
				purpose: "Read recent logs from the real target.",
			},
			{
				name: "Evaluate",
				url: `http://${listenHost}:${listenPort}/api/evaluate`,
				purpose: "Execute Runtime.evaluate in the real target context.",
			},
			{
				name: "CDP Target List",
				url: `http://${listenHost}:${listenPort}/json/list`,
				purpose: "Only for CDP clients that need a target list.",
			},
		],
		shouldNotRead: [
			{
				name: "Original Inspector Container",
				url: input ?? "http://localhost:9222/devtools/inspector.html?...",
				reason:
					"This is the DevTools frontend shell, not the actual NetEase Cloud Music page.",
			},
			{
				name: "Proxied Inspector Container",
				url: `http://${listenHost}:${listenPort}/devtools/inspector.html?...`,
				reason:
					"Opening this still enters the DevTools frontend container and can mislead AI into reading the wrong page.",
			},
		],
	};

	if (runtimeClient) {
		runtimeClient.Runtime.consoleAPICalled((params: unknown) => {
			const payload = params as RuntimeConsoleCall;
			appendLog({
				kind: "console",
				level: payload.type ?? "log",
				timestamp: formatTimestamp(payload.timestamp),
				text: formatArgs(payload.args),
				location: formatTopFrame(payload.stackTrace) || undefined,
			});
		});

		runtimeClient.Runtime.exceptionThrown((params: unknown) => {
			const payload = params as RuntimeExceptionThrown;
			const details = payload.exceptionDetails;
			const text =
				details?.exception?.description ??
				(typeof details?.exception?.value === "string"
					? details.exception.value
					: details?.text) ??
				"Unknown exception";
			const location = details?.url
				? `${details.url}:${(details.lineNumber ?? 0) + 1}:${(details.columnNumber ?? 0) + 1}`
				: formatTopFrame(details?.stackTrace) || undefined;

			appendLog({
				kind: "exception",
				level: "error",
				timestamp: formatTimestamp(payload.timestamp),
				text,
				location,
			});
		});

		runtimeClient.Log.entryAdded((params: unknown) => {
			const payload = params as LogEntryAdded;
			const entry = payload.entry;
			appendLog({
				kind: "log",
				level: entry?.level ?? "info",
				timestamp: new Date().toISOString(),
				text: entry?.text ?? "",
				location: entry?.url
					? `${entry.url}:${(entry.lineNumber ?? 0) + 1}`
					: entry?.source,
			});
		});

		await runtimeClient.Runtime.enable();
		await runtimeClient.Log.enable();
	}

	const readJsonBody = async <T>(req: Parameters<typeof createServer>[0]): Promise<T> => {
		const chunks: Buffer[] = [];
		for await (const chunk of req) {
			chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
		}
		const text = Buffer.concat(chunks).toString("utf8");
		return (text ? JSON.parse(text) : {}) as T;
	};

	const server = createServer(async (req, res) => {
		try {
			const requestUrl = new URL(req.url ?? "/", `http://${listenHost}:${listenPort}`);
			const pathname = requestUrl.pathname;
			if (pathname === "/healthz") {
				res.writeHead(200, { "content-type": "application/json; charset=utf-8" });
				res.end(JSON.stringify({ ok: true }));
				return;
			}

			if (pathname === "/api/bootstrap") {
				res.writeHead(200, { "content-type": "application/json; charset=utf-8" });
				res.end(JSON.stringify(bootstrapPayload, null, 2));
				return;
			}

			if (pathname === "/api/target") {
				res.writeHead(200, { "content-type": "application/json; charset=utf-8" });
				res.end(JSON.stringify(formatTargetSummary(resolved), null, 2));
				return;
			}

			if (pathname.startsWith("/api/logs")) {
				const recent = Number.parseInt(
					requestUrl.searchParams.get("recent") ?? "200",
					10,
				);
				const entries =
					recent > 0 ? logBuffer.slice(-recent) : [...logBuffer];
				res.writeHead(200, { "content-type": "application/json; charset=utf-8" });
				res.end(
					JSON.stringify(
						{
							target: formatTargetSummary(resolved),
							total: logBuffer.length,
							entries,
						},
						null,
						2,
					),
				);
				return;
			}

			if (pathname === "/api/evaluate" && req.method === "POST") {
				if (!runtimeClient) {
					throw new Error("当前代理没有可用的 Runtime 连接");
				}

				const body = await readJsonBody<{
					expression?: string;
					awaitPromise?: boolean;
					returnByValue?: boolean;
				}>(req);

				if (!body.expression) {
					res.writeHead(400, {
						"content-type": "application/json; charset=utf-8",
					});
					res.end(JSON.stringify({ error: "Missing expression" }, null, 2));
					return;
				}

				const result = await runtimeClient.send("Runtime.evaluate", {
					expression: body.expression,
					awaitPromise: body.awaitPromise ?? true,
					returnByValue: body.returnByValue ?? true,
				});

				res.writeHead(200, { "content-type": "application/json; charset=utf-8" });
				res.end(JSON.stringify(result, null, 2));
				return;
			}

			if (pathname === "/json" || pathname.startsWith("/json/list")) {
				const upstream = (await proxyJsonRequest(
					resolved.endpoint,
					"/json/list",
				)) as DevtoolsListTarget[];
				const filtered = upstream.filter((target) => {
					if (!target.webSocketDebuggerUrl) return false;
					if (targetId && target.id !== targetId) return false;
					if (!exposeAll && resolved.targetId && target.id !== resolved.targetId) {
						return false;
					}
					return true;
				});
				let rewritten = filtered.map((target) =>
					rewriteTarget(target, listenHost, listenPort),
				);
				if (rewritten.length === 0) {
					const synthetic = createSyntheticTarget(
						resolved,
						listenHost,
						listenPort,
					);
					if (synthetic) {
						rewritten = [synthetic];
					}
				}
				res.writeHead(200, { "content-type": "application/json; charset=utf-8" });
				res.end(JSON.stringify(rewritten, null, 2));
				return;
			}

			if (pathname.startsWith("/json/version")) {
				const upstream = (await proxyJsonRequest(
					resolved.endpoint,
					"/json/version",
				)) as Record<string, unknown>;
				const browserWs = upstream.webSocketDebuggerUrl;
				const rewritten =
					typeof browserWs === "string"
						? {
								...upstream,
								webSocketDebuggerUrl: toProxyWebSocketUrl(
									listenHost,
									listenPort,
									browserWs,
								),
							}
						: upstream;
				res.writeHead(200, { "content-type": "application/json; charset=utf-8" });
				res.end(JSON.stringify(rewritten, null, 2));
				return;
			}

			if (pathname.startsWith("/json/protocol")) {
				const upstream = await proxyJsonRequest(resolved.endpoint, "/json/protocol");
				res.writeHead(200, { "content-type": "application/json; charset=utf-8" });
				res.end(JSON.stringify(upstream));
				return;
			}

			if (pathname === "/") {
				const html = `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>DevTools AI Proxy Guide</title>
  <style>
    :root {
      --panel: rgba(255, 250, 242, 0.94);
      --ink: #1e2422;
      --muted: #5f6d67;
      --ok: #1d7a4a;
      --bad: #a03232;
      --line: #dccfb8;
      --accent: #b2542f;
    }
    body { margin: 0; font-family: "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif; background: radial-gradient(circle at top, #fff8ef, #efe2ce 70%); color: var(--ink); }
    main { max-width: 1040px; margin: 0 auto; padding: 28px 18px 40px; }
    .hero, .card { border: 1px solid var(--line); border-radius: 22px; background: var(--panel); box-shadow: 0 16px 48px rgba(55, 36, 19, 0.08); }
    .hero { padding: 26px; margin-bottom: 18px; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 16px; }
    .card { padding: 20px; }
    .good h2 { color: var(--ok); }
    .bad h2 { color: var(--bad); }
    h1, h2 { margin: 0 0 12px; }
    p, li { line-height: 1.6; color: var(--muted); }
    ul { margin: 10px 0 0; padding-left: 18px; }
    li { margin: 10px 0; }
    code, pre { font-family: "Cascadia Code", Consolas, monospace; background: #2e241c; color: #f7ede3; border-radius: 12px; }
    code { padding: 2px 6px; }
    pre { margin: 14px 0 0; padding: 14px; overflow: auto; white-space: pre-wrap; word-break: break-word; }
    .badge { display: inline-block; margin-bottom: 12px; padding: 5px 10px; border-radius: 999px; background: #f0decb; color: var(--accent); font-size: 12px; font-weight: 700; letter-spacing: 0.04em; text-transform: uppercase; }
  </style>
</head>
<body>
  <main>
    <section class="hero">
      <div class="badge">AI Safe Entry</div>
      <h1>AI 应该读取真实 target，而不是 inspector 容器</h1>
      <p>这个页面直接告诉 AI 哪些接口应该读取，哪些不应该读取。AI 如果再次打开 <code>inspector.html</code>，就会重新掉回 DevTools 容器页，而不是网易云本体。</p>
      <pre>${escapeHtml(JSON.stringify(bootstrapPayload.target, null, 2))}</pre>
    </section>
    <section class="grid">
      <article class="card good">
        <h2>AI 应该读取</h2>
        <ul>${bootstrapPayload.shouldRead.map((item) => `<li><strong>${escapeHtml(item.name)}</strong><br><code>${escapeHtml(item.url)}</code><br>${escapeHtml(item.purpose)}</li>`).join("")}</ul>
      </article>
      <article class="card bad">
        <h2>AI 不应该读取</h2>
        <ul>${bootstrapPayload.shouldNotRead.map((item) => `<li><strong>${escapeHtml(item.name)}</strong><br><code>${escapeHtml(item.url)}</code><br>${escapeHtml(item.reason)}</li>`).join("")}</ul>
      </article>
    </section>
    <section class="card" style="margin-top: 16px;">
      <h2>推荐顺序</h2>
      <ul>
        <li>先读 <code>/api/bootstrap</code>，确认安全入口。</li>
        <li>再读 <code>/api/target</code>，确认当前 target 是不是 <code>orpheus://...</code>。</li>
        <li>实时监控读 <code>/api/logs</code>。</li>
        <li>实时控制用 <code>/api/evaluate</code>。</li>
        <li>只有 CDP 客户端才需要 <code>/json/list</code>。</li>
      </ul>
    </section>
  </main>
</body>
</html>`;
				res.writeHead(200, { "content-type": "text/html; charset=utf-8" });
				res.end(html);
				return;
			}

			if (pathname === "/" || pathname === "/targets") {
				res.writeHead(200, { "content-type": "application/json; charset=utf-8" });
				res.end(
					JSON.stringify(
						{
							message:
								"这是给 MCP / CDP 客户端和 AI 调试代理用的真实 target 入口。不要再打开 inspector.html 套娃。",
							target: formatTargetSummary(resolved),
							listen: `http://${listenHost}:${listenPort}`,
							api: {
								target: `http://${listenHost}:${listenPort}/api/target`,
								logs: `http://${listenHost}:${listenPort}/api/logs`,
								evaluate: `http://${listenHost}:${listenPort}/api/evaluate`,
							},
						},
						null,
						2,
					),
				);
				return;
			}

			if (pathname.startsWith("/devtools/")) {
				const upstreamUrl = `${resolved.endpoint.secure ? "https" : "http"}://${resolved.endpoint.host}:${resolved.endpoint.port}${pathname}${requestUrl.search}`;
				const upstreamRes = await fetch(upstreamUrl);
				const contentType = upstreamRes.headers.get("content-type") || "text/html";
				let body = await upstreamRes.text();
				
				// 重写 WebSocket URL 为代理地址
				if (contentType.includes("text/html") || contentType.includes("application/javascript")) {
					const proxyHost = listenHost === "0.0.0.0" ? requestUrl.hostname || listenHost : listenHost;
					body = body
						.replace(/ws:\/\/127\.0\.0\.1:9222/g, `ws://${proxyHost}:${listenPort}`)
						.replace(/ws:\/\/localhost:9222/g, `ws://${proxyHost}:${listenPort}`)
						.replace(/"webSocketDebuggerUrl"\s*:\s*"ws:\/\/[^"]+"/g, `"webSocketDebuggerUrl":"ws://${proxyHost}:${listenPort}/devtools/page/${resolved.targetId || ""}"`);
				}
				
				res.writeHead(upstreamRes.status, { "content-type": contentType });
				res.end(body);
				return;
			}

			res.writeHead(404, { "content-type": "application/json; charset=utf-8" });
			res.end(JSON.stringify({ error: "Not found", path: pathname }, null, 2));
		} catch (error) {
			res.writeHead(500, { "content-type": "application/json; charset=utf-8" });
			res.end(
				JSON.stringify(
					{
						error: "Proxy error",
						message: error instanceof Error ? error.message : String(error),
					},
					null,
					2,
				),
			);
		}
	});

	const wss = new WebSocketServer({ noServer: true });
	server.on("upgrade", (req, socket, head) => {
		const pathnameAndSearch = req.url ?? "/";
		if (!pathnameAndSearch.startsWith("/devtools/")) {
			socket.destroy();
			return;
		}

		wss.handleUpgrade(req, socket, head, (clientSocket) => {
			const upstreamUrl = toUpstreamWebSocketUrl(
				resolved.endpoint,
				pathnameAndSearch,
			);
			const upstreamSocket = new WebSocket(upstreamUrl);

			clientSocket.on("message", (data, isBinary) => {
				if (upstreamSocket.readyState === WebSocket.OPEN) {
					upstreamSocket.send(data, { binary: isBinary });
				}
			});

			upstreamSocket.on("message", (data, isBinary) => {
				if (clientSocket.readyState === WebSocket.OPEN) {
					clientSocket.send(data, { binary: isBinary });
				}
			});

			const closeBoth = () => {
				if (clientSocket.readyState < WebSocket.CLOSING) {
					clientSocket.close();
				}
				if (upstreamSocket.readyState < WebSocket.CLOSING) {
					upstreamSocket.close();
				}
			};

			clientSocket.on("close", closeBoth);
			clientSocket.on("error", closeBoth);
			upstreamSocket.on("close", closeBoth);
			upstreamSocket.on("error", closeBoth);
		});
	});

	server.listen(listenPort, listenHost, () => {
		console.log(
			`[devtools:proxy] 已启动真实 target 代理: http://${listenHost}:${listenPort}`,
		);
		console.log(
			`[devtools:proxy] MCP / 自动测试 / AI 请连接这个代理，不要再连 inspector.html 页面本身。`,
		);
		console.log(JSON.stringify(formatTargetSummary(resolved), null, 2));
	});
}

main().catch((error) => {
	console.error("[devtools:proxy] 启动失败:", error);
	process.exitCode = 1;
});
